# configurations
# 详情请参考：https://halo.run/develop/theme.html#settings-yaml
genernal:
  label: 基本设置
  items:
    home_title:
      name: home_title
      label: 首页展示博客名
      type: text
      placeholder: '用于首页展示名字'
      description: '注意：如填写，会覆盖原有博客名'
    home_description:
      name: home_description
      label: 首页描述
      type: text
      placeholder: '用于首页描述'
    base_color:
      name: base_color
      label: 网站主题色
      type: color
      default: '#2474b5'
      placeholder: '网站主题色'
    home_cover:
      name: home_cover
      label: 首页背景
      type: attachment
      default: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
    enabled_index_cover_height:
      name: enabled_index_cover_height
      label: 首页开启全屏图片
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    header_logoimg:
      name: header_logoimg
      label: 菜单 Logo
      type: attachment
    header_logo_height:
      name: header_logo_height
      label: 菜单 Logo 高度
      type: text
      placeholder: '比如: 20px'
    post_list_style:
      name: post_list_style
      label: 首页文章风格
      type: radio
      data-type: string
      default: standard
      options:
        - value: standard
          label: 标准
        - value: simple
          label: 简单
        - value: card
          label: 卡片
    card_random_cover:
      name: card_random_cover
      label: 卡篇文章风格无图片随机选择图片
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
      description: '开启前请确保有图片名类似 thumbnail-{number}.png 的图片在图库中({number} 的取值为0-10), 否则图片会全黑'
    auto_night_mode:
      name: auto_night_mode
      label: 暗夜模式总开关
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    night_mode:
      name: night_mode
      label: 暗夜模式顶部按钮(需要先打开暗黑模式总开关)
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    night_mode_start_time:
      name: night_mode_start_time
      label: 暗夜模式开始时间
      type: text
      placeholder: '暗夜模式开始时间 默认18'
      description: '注意：24小时制的小时. 比如:18'
    night_mode_end_time:
      name: night_mode_end_time
      label: 暗夜模式结束时间
      type: text
      placeholder: '暗夜模式结束时间,  默认6'
      description: '注意：24小时制的小时. 比如:6'
    top_search:
      name: top_search
      label: 搜索
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    visit_statistics:
      name: visit_statistics
      label: 用户访问统计
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    post_summary:
      name: post_summary
      label: 首页文章摘要
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    custom_scroller:
      name: custom_scroller
      label: 自定义滚动条
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    custom_scroller_color:
      name: custom_scroller_color
      label: 自定义滚动条颜色
      type: color
      default: '#2474b5'
      placeholder: '网站主题色'
    Icp:
      name: Icp
      label: 'ICP 备案号'
      type: text
      placeholder: '填入 ICP 备案号，没有则不填. '
    PublicSecurityRecord:
      name: PublicSecurityRecord
      label: '网安备案号'
      type: text
      placeholder: '填入网安备案号代码，没有则不填'
    QR_code_zfb:
      name: QR_code_zfb
      label: '支付宝二维码链接'
      type: attachment
      placeholder: '支付宝收款二维码链接，不填不显示'
    QR_code_wx:
      name: QR_code_wx
      label: '微信二维码链接'
      type: attachment
      placeholder: '微信收款二维码链接，不填不显示'
head_img:
  label: 网页首部图片
  items:
    archives_patternimg:
      name: archives_patternimg
      label: 归档页面头部装饰图
      type: attachment
      default: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
    links_patternimg:
      name: links_patternimg
      label: 友情链接页面头部装饰图
      type: attachment
      default: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
    tag_patternimg:
      name: tag_patternimg
      label: 标签页面头部装饰图
      type: attachment
      default: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
    categories_patternimg:
      name: categories_patternimg
      label: 分类页面头部装饰图
      type: attachment
      default: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
    journals_patternimg:
      name: journals_patternimg
      label: 日志下文章页面头部装饰图
      type: attachment
      default: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
    photos_patternimg:
      name: photos_patternimg
      label: 相册页面头部装饰图
      type: attachment
      default: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
    links_placeholder:
      name: links_placeholder
      label: 友情链接默认用户头像
      type: attachment
      default: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
index_post:
  label: 首页文章页
  items:
    index_post_toc:
      name: index_post_toc
      label: 文章描述
      type: text
      default: 最新文章
post:
  label: 文章页
  items:
    post_toc:
      name: post_toc
      label: 目录
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    post_nepre:
      name: post_nepre
      label: 下一篇
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    pagenav_style:
      name: pagenav_style
      label: 分页模式
      type: radio
      data-type: string
      default: ajax
      options:
        - value: ajax
          label: ajax加载
        - value: np
          label: 上一页和下一页
    open_read_progress:
      name: open_read_progress
      label: 是否使用阅读进度条
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 显示
        - value: false
          label: 关闭
    progress_color:
      name: progress_color
      label: 阅读进度条颜色
      type: color
      default: '#2474b5'
      placeholder: '阅读进度条颜色'
    post_max_wdth:
      name: post_max_wdth
      label: 文章最大宽度
      type: text
      default: '800px'
      placeholder: '文章最大宽度, 比如: 800px'
    content_font_size:
      name: content_font_size
      label: 文章正文字体大小
      type: text
      default: '1.12rem'
      placeholder: '文章正文字体大小, 比如: 1.16rem 或 14px'
    content_line_height:
      name: content_line_height
      label: 文章正文高度
      type: text
      default: '2rem'
      placeholder: '文章正文高度, 比如: 2rem 或 14px'
    enabled_visual_height:
      name: enabled_visual_height
      label: 文章页开启全屏图片
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    social_share:
      name: social_share
      label: 开启文章分享
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 是
        - value: false
          label: 否
    share_disabeld:
      name: share_disabeld
      label: 分享禁用
      type: text
      default: 'google,twitter,facebook'
      placeholder: '文章分享禁用社交软件'
      description: '文章分享禁用社交软件,比如: google,twitter,facebook,weibo,qq,tencent,qzone,linkedin,wechat,douban,diandian'
    enabled_mathjax:
      name: enabled_mathjax
      label: Mathjax
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    enabled_mermaid:
      name: enabled_mermaid
      label: Mermaid
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    copyright_clean:
      name: copyright_clean
      label: 简洁版权信息
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
custom:
  label: 自定义
  items:
    TimeStatistics:
      name: TimeStatistics
      label: '站点运行时间统计'
      type: text
      description: '填入起始时间，格式：月/日/年 时:分:秒，如08/20/2018 12:00:00'
    Custom_css_src:
      name: Custom_css_src
      label: '自定义外部 css 文件链接'
      type: text
      description: '填入 css 文件链接，不需要 style 标签'
    Custom_css:
      name: Custom_css
      label: '自定义 css 代码'
      type: textarea
      description: '写入 css 代码，不需要 style 标签'
    Custom_js_head:
      name: Custom_js_head
      label: 'head 结束标签前自定义 js 代码'
      type: textarea
      description: '写入 js 代码，不需要 script 标签'
    Custom_js_foot_src:
      name: Custom_js_foot_src
      label: 'body 结束标签前自定义外部 js 文件链接'
      type: text
      description: '填入 js 文件链接，需要 script 标签'
    Custom_js_foot:
      name: Custom_js_foot
      label: 'body 结束标签前自定义js代码'
      type: textarea
      description: '写入 js 代码，不需要 script 标签'
title:
  label: 页面标题
  items:
    links_title:
      name: links_title
      label: 友链页面标题
      type: text
      default: 友链
    jounarls_title:
      name: jounarls_title
      label: 日志页面标题
      type: text
      default: 日志
    tags_title:
      name: tags_title
      label: 标签页面标题
      type: text
      default: 标签列表
    categories_title:
      name: categories_title
      label: 分类列表页面标题
      type: text
      default: 分类列表
    achieve_title:
      name: achieve_title
      label: 归档页面标题
      type: text
      default: 归档
    photos_title:
      name: photos_title
      label: 相册页面标题
      type: text
      default: 相册
social:
  label: 社交网络
  items:
    #    wechat:
    #      name: wechat
    #      label: 微信二维码
    #      type: attachment
    sina:
      name: sina
      label: 新浪微博
      type: text
      placeholder: '用于展示底部新浪微博社交信息'
      description: '新浪微博主页链接'
    jianshu:
      name: jianshu
      label: 简书
      type: text
      placeholder: '用于展示底部简书社交信息'
      description: '简书用户名'
    bilibili:
      name: bilibili
      label: b站
      type: text
      placeholder: '用于展示底部 bilibili 社交信息'
      description: 'bilibili 主页链接'
    qq:
      name: qq
      label: 腾讯 QQ
      type: text
      placeholder: '用于展示底部 QQ 社交信息'
      description: 'QQ 号码'
    github:
      name: github
      label: Github
      type: text
      placeholder: '用于展示底部 Github 社交信息'
      description: 'GitHub 主页链接'
    zhihu:
      name: zhihu
      label: 知乎
      type: text
      placeholder: '用于展示底部知乎社交信息'
      description: '知乎主页链接'
    mail:
      name: mail
      label: 邮箱
      type: text
      placeholder: '用于展示底部邮箱社交信息'
      description: '邮箱地址'
    rss:
      name: rss
      label: 订阅按钮
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
experimental:
  label: 实验性功能
  items:
    pjax_enabled:
      name: pjax_enabled
      label: 全局 Pjax
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    Aplayer:
      name: Aplayer
      label: Aplayer吸底播放器
      type: text
      placeholder: '网易云歌单id'
      description: '网易云歌单id, 比如: 60198. 暂时就只能这样子了, 后面再优化吧'
    xiang_ying_xiong_zhi_jing:
      name: xiang_ying_xiong_zhi_jing
      label: 向英雄致敬, 愿精神长存
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
      description: '惟愿此功能永远不会被使用'
other:
  label: 其他
  items:
    notice_enable:
      name: notice_enable
      label: 是否开启公告
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    notice:
      name: notice
      label: 公告
      type: textarea
      placeholder: 公告内容，在首页展示
    top_feature:
      name: top_feature
      label: 是否开启聚焦
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    feature_title:
      name: feature_title
      label: 聚焦标题
      type: text
      default: '置顶文章'
      placeholder: '默认为聚焦，你也可以修改为其他，当然不能当广告用！不允许！！'
    feature1_img:
      name: feature1_img
      label: 聚焦图一
      type: attachment
      placeholder: '尺寸257px*160px'
    feature1_link:
      name: feature1_link
      label: 聚焦图一链接
      type: text
      default: '#'
    feature1_title:
      name: feature1_title
      label: 聚焦图一标题
      type: text
      default: 'feature1'
    feature1_text:
      name: feature1_text
      label: 聚焦图一内容
      type: textarea
      placeholder: '这里填写图一的内容'
    feature2_img:
      name: feature2_img
      label: 聚焦图二
      type: attachment
      placeholder: '尺寸257px*160px'
    feature2_link:
      name: feature2_link
      label: 聚焦图二链接
      type: text
      default: '#'
    feature2_title:
      name: feature2_title
      label: 聚焦图二标题
      type: text
      default: 'feature2'
    feature2_text:
      name: feature2_text
      label: 聚焦图二内容
      type: textarea
      placeholder: '这里填写图二的内容'
    feature3_img:
      name: feature3_img
      label: 聚焦图三
      type: attachment
      placeholder: '尺寸257px*160px'
    feature3_link:
      name: feature3_link
      label: 聚焦图三链接
      type: text
      default: '#'
    feature3_title:
      name: feature3_title
      label: 聚焦图三标题
      type: text
      default: 'feature3'
    feature3_text:
      name: feature3_text
      label: 聚焦图三内容
      type: textarea
      placeholder: '这里填写图三的内容'